# Generated by Django 4.1.4 on 2023-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saint', '0002_rename_dob_students_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
